
my_list = ['trip_dur=0',
           'getoff_dur=0',
           'flutspeed_dur=0',
           'enemyspeed_dur=0',
           'give_dur=0',
           'collected_dur=0',
           'eco_dur=0',
           'sucksuck_dur=0',
           'die_dur=0',
           'topoint_dur=0',
           'randompoint_dur=0',
           'tp_dur=0',
           'shift_dur=0',
           'movetojak_dur=0',
           'ouch_dur=0',
           'burn_dur=0',
           'hp_dur=0',
           'melt_dur=0',
           'endlessfall_dur=0',
           'deload_dur=0',
           'quickcam_dur=0',
           'moveplantboss_dur=0',
           'moveplantboss2_dur=0',
           'basincell_dur=0',
           'resetactors_dur=0',
           'repl_dur=0',
           'debug_dur=0',
           'debug_cd=0',
           'melt_cd=0',
           'endlessfall_cd=0',
           'burn_cd=0',
           'shift_cd=0',
           'randompoint_cd=0',
           'collected_cd=0',
           'ghostjak_cd=0',
           'save_cd=0',
           'save_dur=0',
           'resetcooldowns_cd=0',
           'resetcooldowns_dur=0',
           'cd_dur=0',
           'cd_cd=0',
           'dur_dur=0',
           'dur_cd=0',
           'enable_cd=0',
           'disable_cd=0',
           'disable_dur=0',
           'enable_dur=0',
           'flatjak_cd=0',
           'smalljak_cd=0',
           'bigjak_cd=0',
           'widejak_cd=0',
           'actorson_cd=0',
           'actorson_dur=0',
           'actorsoff_cd=0',
           'actorsoff_dur=0',
           'unzoom_dur=0',
           'drown_cd=0',
           'drown_dur=0',
           'press_dur=0',
           'setpoint_dur=0',
           'fixoldsave_dur=0',
           'fixoldsave_cd=0',
           'lang_dur=0',
           'resetcooldowns=t',
           'cd=t',
           'dur=t',
           'enable=t',
           'disable=t']







for item in my_list:
    key, value = item.split("=")
    print(f'env_file_updater.update(["{key}"], "{value}")')